export const endpoints = {
  captchaImage: "/api/captcha/image",
  adminLogin: "/api/admin/login",
  adminChangePassword: "/api/admin/change-password",
  adminList: "/api/admin/list",
  adminRoles: "/api/admin/roles",
  adminCreate: "/api/admin/create",
  adminEdit: "/api/admin/edit",
  adminDelete: "/api/admin/delete",
  adminLogList: "/api/admin/log/list",
  roleList: "/api/admin/role/list",
  rolePermissions: "/api/admin/role/permissions",
  roleDetail: "/api/admin/role/detail",
  roleCreate: "/api/admin/role/create",
  roleEdit: "/api/admin/role/edit",
  roleDelete: "/api/admin/role/delete",

  dashboardOverview: "/api/dashboard/overview",
  operationReportList: "/api/dashboard/operation-report/list",
  operationReportExport: "/api/dashboard/operation-report/export",

  uploadImage: "/api/common/upload/image",

  paymentQrcodeList: "/api/operation/payment-qrcode/list",
  paymentQrcodeSave: "/api/operation/payment-qrcode/save",
  homeCategoryDetail: "/api/operation/home-category/detail",
  homeCategorySave: "/api/operation/home-category/save",
  bannerList: "/api/operation/banner/list",
  bannerAdd: "/api/operation/banner/add",
  bannerDetail: "/api/operation/banner/detail",
  bannerEdit: "/api/operation/banner/edit",
  bannerDelete: "/api/operation/banner/delete",
  contactDetail: "/api/operation/contact-config/detail",
  contactSave: "/api/operation/contact-config/save",
  exchangeRateDetail: "/api/operation/exchange-rate/detail",
  exchangeRateSave: "/api/operation/exchange-rate/save",

  userList: "/api/user/list",
  userAdd: "/api/user/add",
  userDetail: "/api/user/detail",
  userEdit: "/api/user/edit",
  userPasswordEdit: "/api/user/password/edit",
  rechargeList: "/api/user/recharge/list",
  rechargeConfirm: "/api/user/recharge/confirm",
  rechargeCancel: "/api/user/recharge/cancel",
  balanceLogList: "/api/user/balance-log/list",

  productCategoryList: "/api/product/category/list",
  productCategoryAdd: "/api/product/category/add",
  productCategoryDetail: "/api/product/category/detail",
  productCategoryEdit: "/api/product/category/edit",
  productCategoryDelete: "/api/product/category/delete",
  productList: "/api/product/list",
  productAdd: "/api/product/add",
  productDetail: "/api/product/detail",
  productEdit: "/api/product/edit",
  productDelete: "/api/product/delete",

  productOrderList: "/api/product/order/list",
  productOrderDetail: "/api/product/order/detail",
  expressCompanies: "/api/product/order/express-companies",
  productOrderShip: "/api/product/order/ship",

  blessItemList: "/api/blessing/item/list",
  blessItemAll: "/api/blessing/item/all",
  blessItemAdd: "/api/blessing/item/add",
  blessItemDetail: "/api/blessing/item/detail",
  blessItemEdit: "/api/blessing/item/edit",
  blessItemDelete: "/api/blessing/item/delete",
  blessDynamicList: "/api/blessing/dynamic/list",
  blessDynamicCreate: "/api/blessing/dynamic/create",
  blessOrderList: "/api/blessing/order/list",

  sacrificeCategoryList: "/api/sacrifice/category/list",
  sacrificeCategoryAll: "/api/sacrifice/category/all",
  sacrificeCategoryAdd: "/api/sacrifice/category/add",
  sacrificeCategoryEdit: "/api/sacrifice/category/edit",
  tributeList: "/api/sacrifice/tribute/list",
  tributeAdd: "/api/sacrifice/tribute/add",
  tributeDetail: "/api/sacrifice/tribute/detail",
  tributeEdit: "/api/sacrifice/tribute/edit",
  tributeDelete: "/api/sacrifice/tribute/delete",
  sacrificeDynamicList: "/api/sacrifice/dynamic/list",
  sacrificeDynamicCreate: "/api/sacrifice/dynamic/create",
  cemeteryList: "/api/sacrifice/cemetery/list",
  cemeteryCreate: "/api/sacrifice/cemetery/create",
  sacrificeOrderList: "/api/sacrifice/order/list",

  metaphysicsCategoryList: "/api/metaphysics/category/list",
  metaphysicsCategoryAdd: "/api/metaphysics/category/add",
  metaphysicsCategoryEdit: "/api/metaphysics/category/edit",
  metaphysicsCategoryDelete: "/api/metaphysics/category/delete",

  metaphysicsArticleList: "/api/metaphysics/article/list",
  metaphysicsArticleDetail: "/api/metaphysics/article/detail",
  metaphysicsArticleCreate: "/api/metaphysics/article/create",
  metaphysicsArticleEdit: "/api/metaphysics/article/edit",
  metaphysicsArticleDelete: "/api/metaphysics/article/delete",

  teachingVideoList: "/api/teaching/video/list",
  teachingVideoCreate: "/api/teaching/video/create",
  teachingVideoEdit: "/api/teaching/video/edit",
  teachingVideoDelete: "/api/teaching/video/delete",

  teachingCoursewareList: "/api/teaching/courseware/list",
  teachingCoursewareDetail: "/api/teaching/courseware/detail",
  teachingCoursewareCreate: "/api/teaching/courseware/create",
  teachingCoursewareEdit: "/api/teaching/courseware/edit",
  teachingCoursewareDelete: "/api/teaching/courseware/delete",

  teachingOne2OneList: "/api/teaching/one-on-one/list",
  teachingOne2OneDetail: "/api/teaching/one-on-one/detail",
  teachingOne2OneCreate: "/api/teaching/one-on-one/create",
  teachingOne2OneEdit: "/api/teaching/one-on-one/edit",
  teachingOne2OneDelete: "/api/teaching/one-on-one/delete",

  teachingLiveList: "/api/teaching/live/list",
  teachingLiveCreate: "/api/teaching/live/create",
  teachingLiveEdit: "/api/teaching/live/edit",
  teachingLiveDelete: "/api/teaching/live/delete",
} as const;

